name: rush_prompt
description: A library for creating CLI prompts.
version: 1.0.0

environment:
  sdk: '>=2.15.0-268.18.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0

dependencies:
  dart_console: ^1.0.0
