name: rush_cli
description: A new and improved way of building MIT AI2 extensions.
version: 2.0.0-rc01
homepage: https://github.com/shreyashsaitwal/rush-cli

executables:
  rush: rush.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  lints: ^2.0.1

dependencies:
  archive: ^3.3.6
  args: ^2.3.2
  checked_yaml: ^2.0.2
  collection: ^1.17.1
  crypto: ^3.0.2
  dart_console: ^1.1.2
  get_it: ^7.2.0
  github: ^9.9.0
  hive: ^2.2.3
  http: ^0.13.5
  interact: ^2.1.1
  json_annotation: ^4.8.0
  path: ^1.8.3
  recase: ^4.1.0
  tint: ^2.1.0
  xml2json: ^5.3.6
  xrange: ^2.0.0

dependency_overrides:
  tint:
    git:
      url: https://github.com/shreyashsaitwal/tint
      ref: main
