name: rush_cli
description: A new and improved way of building MIT AI2 extensions.
version: 2.0.0-beta
homepage: https://github.com/shreyashsaitwal/rush-cli

executables:
  rush: rush.dart

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.1.0
  json_serializable: ^6.2.0
  lints: ^1.0.1

publish_to: none

dependencies:
  archive: ^3.1.2
  args: ^2.0.0
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  dart_console: ^1.0.0
  dio: ^4.0.0-beta5
  hive: ^2.0.0
  json_annotation: ^4.5.0
  meta: ^1.3.0
  path: ^1.8.0
  process_runner: ^4.0.1
  resolver:
    path: ./packages/resolver
  rush_prompt:
    path: ./packages/rush_prompt
