name: rush_cli
description: A new and improved way of building MIT AI2 extensions.
version: 2.0.0-beta
homepage: https://github.com/shreyashsaitwal/rush-cli

executables:
  rush: rush.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  build_version: ^2.1.1
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  lints: ^2.0.0

publish_to: none

dependencies:
  archive: ^3.3.1
  args: ^2.0.0
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  crypto: ^3.0.2
  dart_console: ^1.1.2
  get_it: ^7.2.0
  github: ^9.4.0
  hive: ^2.2.3
  http: ^0.13.5
  interact: ^2.1.1
  json_annotation: ^4.6.0
  path: ^1.8.2
  recase: ^4.1.0
  tint: ^2.0.0
  xml2json: ^5.3.4
  xrange: ^2.0.0

dependency_overrides:
  tint:
    git:
      url: https://github.com/shreyashsaitwal/tint
      ref: main
