name: resolver
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  freezed_annotation: ^2.0.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  path: ^1.8.0
  xml2json: ^5.3.2

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  lints: ^1.0.0
  test: ^1.16.0
