name: resolver
description: A Dart library to resolver artifacts from remote Maven repositories.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  path: ^1.8.0
  xml2json: ^5.3.2

dev_dependencies:
  lints: ^1.0.0
