name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            os_short: win
          - os: macos-latest
            os_short: macos
          - os: ubuntu-latest
            os_short: linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Get deps
        run: dart pub get

      - name: Build the executable
        shell: bash
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh -v 1.2.0 -t ${{ secrets.GH_PAT }}

      - name: Get jq
        shell: bash
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then sudo apt-get install jq; fi
          if [[ "$OSTYPE" == "darwin"* ]]; then brew install jq; fi
          if [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "msys" ]]; then choco install jq; fi

      - name: Upload exe to rush-pack repo
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}
        shell: bash
        run: |
          chmod +x ./scripts/upload_exe.sh
          ./scripts/upload_exe.sh ${{ secrets.GH_PAT }}

  release:
    needs: [build]
    # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            os_short: win
          - os: macos-latest
            os_short: mac
          - os: ubuntu-latest
            os_short: linux

    runs-on: ubuntu-latest

    env:
      BASE_DIR: build/${{ matrix.os_short }}

    steps:
      - uses: actions/checkout@v2

      - name: Download rush-pack repo
        run: |
          mkdir build
          curl -#Lo build/pack.zip -u "shreyashsaitwal:${{ secrets.GH_PAT }}" https://github.com/shreyashsaitwal/rush-pack/archive/refs/heads/main.zip
          unzip -o build/pack.zip -d build
          rm build/pack.zip

      - name: Add files to base directory
        env:
          PACK_DIR: build/rush-pack-main
        run: |
          mkdir -p $BASE_DIR/exe
          cp -R $PACK_DIR/exe/${{ matrix.os_short }} $BASE_DIR/exe
          cp -R $PACK_DIR/dev-deps $BASE_DIR
          cp -R $PACK_DIR/tools $BASE_DIR

      - name: Create ZIP
        run: |
          cd $BASE_DIR
          zip -r rush-${{ matrix.os_short }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: draft
          files: ${{ env.BASE_DIR }}/rush-${{ matrix.os_short }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
